'use client'
import Navbar from './components/Navs/Navbar'
import '@/styles/globals.scss'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Setting, SettingProps, useSetting} from './docs/cache/settings'
import {Recent} from './docs/cache/recent'
import {useState} from 'react'

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [setting, setSettings] = useState<SettingProps>({
    theme: 'dark',
    showRecent: false,
    showSideBar: true,
    textSize: 16,
  })
  const [recentLinks, setRecentLinks] = useState<{link: string, name: string}[]>([{link: "http://localhost:3000/docs", name: 'docs'}]);
  return (
    <html lang="en" className={setting.theme}>
      <body className={inter.className + 'w-full'}>
        <Setting.Provider value={{setting, setSettings}}>
          <Recent.Provider value={{recentLinks, setRecentLinks}}>
            {children}
          </Recent.Provider>
        </Setting.Provider>
      </body>
    </html>
  )
}
